### ISSUE TITLE
Does not correctly parse some expressions of array types for inputs

### ISSUE THREAD

**Issue by MarkRobbo** [common-workflow-language/cwlviewer#23]
The following in CWL:

```
inputs:
  inputExample:
    type:
      type: array
      items: int
```

Currently is resolved to a blank type when shown in the viewer. The correct type should be `int[]`
