### ISSUE TITLE
Support user defined schemas

### ISSUE THREAD

**Issue by MarkRobbo** [common-workflow-language/cwlviewer#96]
Example:

```
requirements:
  - class: InlineJavascriptRequirement
  - $import: sample_schema.yml


inputs:

  samples:
    type:
      type: array
      items: "sample_schema.yml#sample"
```

Should pull in type from external file
